name: source_employee_gx_suite

expectations:
  - expectation_type: expect_table_row_count_to_be_between
    kwargs:
      min_value: 100
      max_value: 120
    meta:
      BasicDatasetExpectation:
        notes: Ensure that the number of rows is within an expected range.

  - expectation_type: expect_column_values_to_be_between
    kwargs:
      column: Employee ID
      min_value: 1001
      max_value: 1200

  - expectation_type: expect_column_values_to_be_in_set
    kwargs:
      column: Department
      value_set:
        - Engineering
        - Marketing
        - Finance
        - Human Resources
    meta:
      ColumnExpectation:
        notes: Ensure valid Department values.

  - expectation_type: expect_column_values_to_match_regex
    kwargs:
      column: Position
      regex: "^[A-Za-z\\s]+$"
    meta:
      ColumnExpectation:
        notes: Ensure Position contains only alphabetic characters and spaces.

  - expectation_type: expect_column_values_to_match_regex
    kwargs:
      column: Location
      regex: "^[A-Za-z\\s]+$"
    meta:
      ColumnExpectation:
        notes: Ensure Location contains only alphabetic characters and spaces.

  - expectation_type: expect_column_mean_to_be_between
    kwargs:
      column: Salary
      min_value: 70000
      max_value: 100000

  - expectation_type: expect_column_median_to_be_between
    kwargs:
      column: Salary
      min_value: 70000
      max_value: 100000

  - expectation_type: expect_column_min_to_be_between
    kwargs:
      column: Salary
      min_value: 68000
      max_value: 108000

  - expectation_type: expect_column_max_to_be_between
    kwargs:
      column: Salary
      min_value: 68000
      max_value: 108000

  - expectation_type: expect_column_values_to_be_between
    kwargs:
      column: Salary
      min_value: 60000
      max_value: 120000
